// PRODUCT
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

// CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const TOGGLE_CART = 'TOGGLE_CART';

export const UPDATE_ARTICLES = 'UPDATE_ARTICLES';
export const UPDATE_POSTS = 'UPDATE_POSTS';